### ISSUE TITLE
Game Rule specification

### ISSUE THREAD

**Issue by vince19972** [vince19972/AlligatorGame#1]
Detail of rule of the game in stage one

👉 [Rules page](https://github.com/vince19972/AlligatorGame/wiki/Rules) is here

**Comment by dreamysun** [comment]
Plz check the first draft of RULES~

**Comment by vince19972** [comment]
I like collaboration version~ it's like mine weeper game!

![mine sweeper](https://media.giphy.com/media/l3V0GQMoaDLVbjXEI/giphy.gif)

**Comment by Annaooh** [comment]
I like the collaboration version too. I was thinking about the kind of 'Reward' or 'Stages' for motivation. We can talk about tomorrow!

**Comment by vince19972** [comment]
In collaboration version, if pressing one bad tooth to lose entire game is too hard, maybe having 3 bad teeth instead? And the winning condition is not to touch all 3 bad teeth, giving players 2 additional chances.

**Comment by vince19972** [comment]
We have 15 people in class. Make 20 teeth.
